repos:
  - "kRxZykRxZy/Scratch-Coding-Hut" # Target repo

files:
  - source: "/src"  # Sync the entire src folder
    dest: "/"    # Place it in the root directory of the target repo
    delete: true # Set to true if you want to delete extra files in the target repo
