name: Clone and Push Repository

on:
  schedule:
    - cron: '*/1 * * * *'  # This cron expression means every minute

jobs:
  clone_and_push:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the current repository (kRxZykRxZy/Scratch-Coding-Hut)
      - name: Checkout the current repository
        uses: actions/checkout@v2

      # Step 2: Clone Scratch-Coding-Hut/Scratch-Coding-Hut repository using PAT
      - name: Clone Scratch-Coding-Hut/Scratch-Coding-Hut repository
        run: |
          git clone https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/Scratch-Coding-Hut/Scratch-Coding-Hut.git
          cd Scratch-Coding-Hut

      # Step 3: Copy files into the current repository, excluding .github folder
      - name: Copy files to current repository, excluding .github folder
        run: |
          shopt -s extglob
          cp -r Scratch-Coding-Hut/!(.github) .

      # Step 4: Commit and push the cloned content into kRxZykRxZy/Scratch-Coding-Hut
      - name: Commit and push changes to kRxZykRxZy/Scratch-Coding-Hut
        run: |
          git add .
          git commit -m "Cloned contents of Scratch-Coding-Hut/Scratch-Coding-Hut excluding .github folder"
          git push https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/kRxZykRxZy/Scratch-Coding-Hut.git main
