name: Clone Scratch-Coding-Hut Repo

on:
  schedule:
    - cron: '*/1 * * * *'  # Run every minute
  workflow_dispatch:  # Allows manual trigger if needed

jobs:
  clone-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the current repository
      uses: actions/checkout@v3

    - name: Clone Scratch-Coding-Hut repository
      run: |
        git clone https://github.com/scratch-coding-hut/Scratch-Coding-Hut.git temp-repo
        rsync -av --progress temp-repo/ ./
        rm -rf temp-repo

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Add content from Scratch-Coding-Hut repo" || echo "No changes to commit"
        git push
