name: Clone Scratch-Coding-Hut Repo

on:
  schedule:
    - cron: '*/1 * * * *'  # Run every minute
  workflow_dispatch:  # Allows manual trigger if needed

jobs:
  clone-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the current repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # Disable automatic credentials

    - name: Clone Scratch-Coding-Hut repository
      run: |
        git clone https://github.com/scratch-coding-hut/Scratch-Coding-Hut.git temp-repo
        rsync -av --progress temp-repo/ ./ --exclude .git/
        rm -rf temp-repo

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

    - name: Check for changes
      run: |
        git add .
        if ! git diff --cached --quiet; then
          echo "Changes detected, committing..."
          git commit -m "Add content from Scratch-Coding-Hut repo"
          git push origin main
        else
          echo "No changes to commit"
        fi
