name: Clone and Push Repository via Python

on:
  schedule:
    - cron: '*/1 * * * *'  # This cron expression means every minute

jobs:
  clone_and_push:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the current repository (kRxZykRxZy/Scratch-Coding-Hut)
      - name: Checkout the current repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install required Python dependencies (requests, gitpython)
      - name: Install dependencies
        run: |
          pip install requests gitpython

      # Step 4: Run the Python script to clone and handle files
      - name: Run Python script to clone and manage files
        run: |
          python3 ./clone_and_manage.py

      # Step 5: Commit and push changes to kRxZykRxZy/Scratch-Coding-Hut
      - name: Commit and push changes to kRxZykRxZy/Scratch-Coding-Hut
        run: |
          git add .
          git commit -m "Cloned contents of Scratch-Coding-Hut/Scratch-Coding-Hut excluding .github folder"
          git push https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/kRxZykRxZy/Scratch-Coding-Hut.git main
