name: Clone Scratch-Coding-Hut Repo

on:
  schedule:
    - cron: '*/1 * * * *'  # Run every minute
  workflow_dispatch:  # Allows manual trigger if needed

jobs:
  clone-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the current repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # Disable automatic credentials to use GITHUB_TOKEN manually

    - name: Clone Scratch-Coding-Hut repository
      run: |
        git clone https://github.com/scratch-coding-hut/Scratch-Coding-Hut.git temp-repo
        rsync -av --progress temp-repo/ ./ --exclude .git/
        rm -rf temp-repo

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Check for changes
      run: |
        git add .
        if ! git diff --cached --quiet; then
          echo "Changes detected, committing..."
          git commit -m "Add content from Scratch-Coding-Hut repo"
        else
          echo "No changes to commit"
          exit 0
        fi

    - name: Push changes to the repository
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
