name: Auto Sync Data from Another Repo

on:
  schedule:
    - cron: '* * * * *' # Runs every minute
  workflow_dispatch: # Manual trigger if needed

jobs:
  sync-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Current Repo
      uses: actions/checkout@v2

    - name: Delete Current Repo Contents
      run: |
        find . -mindepth 1 -maxdepth 1 ! -name ".git" -exec rm -rf {} +

    - name: Download and Extract Target Repo
      run: |
        wget -q https://github.com/Scratch-Coding-Hut/Scratch-Coding-Hut.github.io/archive/refs/heads/main.zip -O main.zip
        unzip -q main.zip
        rsync -av --progress Scratch-Coding-Hut.github.io-main/ . --exclude .git --delete
        rm -rf Scratch-Coding-Hut.github.io-main main.zip

    - name: Configure Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Commit and Push Changes
      run: |
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -m "Sync data from target repo"
        git push
