name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment only on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main  # Ensure you're deploying from the correct branch (main)

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.0
        with:
          branch: gh-pages  # The branch where the content will be deployed (default is gh-pages)
          folder: src  # The folder to deploy (in your case, it's 'src')
          token: ${{ secrets.GITHUB_TOKEN }}  # Automatically used token for authentication
