name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: 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
        issue-message: "Hello and welcome to the repo! Thanks for opening your first issue."
        pr-message: "Hello and welcome to the repo! Thanks for opening your first pull request."
