name: Sync Repos

on:
  schedule:
    - cron: '*/1 * * * *' # Runs every minute
  workflow_dispatch: # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        repository: scratch-coding-hut/Scratch-Coding-Hut
        token: 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

    - name: Push to destination repo
      run: |
        git remote add destination https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/kRxZykRxZy/Scratch-Coding-Hut.git
        git push destination main --force
